---
server:
  name: localhost
  user: sa
  password: Passw0rd!
  database: Loans_2023_01_27

model_dir: '../Models/'

tables:
  -
    name: 'dbo.UnderwritingData'
    primary: 'VIN'
    secondary: 'CreaditScore'
    null_secondary: 0
  -
    name: 'dbo.RawAlgorithmData'
    primary: 'Vin6'
    secondary: 'Score'
    null_secondary: 0


predictions:
  target: 'ProcStatsCd'
  replace:
    CL: 1
    CO: 0
  doSpecial: False
#  special: 'ProfitLoss'
  special: 'DelqPct'

ignore:
  - 'Class_'
  - 'AccountShort'
  - 'CustomerNumber'
  - 'CurBalAmt'
  - 'Customer'
  - 'AdminStatus'
  - 'ResultCD'
  - 'ChargeOffDt'
  - 'PercentageOfPaymentsMade'
  - 'DelqCalcAlert'
  - 'RecyCalcAlert'
  - 'ApplicationNumber'
  - 'CurrentPaymentsMade'
  - 'Name'
  - 'Delq'
  - 'NumberPmnt'

outliers:
  ignore:
    - "Status"
    - "DelqPct"
    - "CreaditScore"
    - "HomeOwner"
    - "Reposessions"
    - "Chageoff"
    - "APR"