entities:
- CreaditScore
- Salary_x
- Recy
- OrigTerm
- Apr
- OpeningBalance
- Salary_y
- EmploymentMonths
- Term
- Payment
- PTI
- VehicleYear
- APR
- LTV
- DTI
- Mileage
- TradelinesTotal
- TradelinesBalance
- Foreclosure
- Reposessions
- Bankrupcies
- Chageoff
- Mortgage
- NinetyDaysDelinquent
- Was180DaysPastDue
- Account150DaysPastDue
- Account180DaysPastDue
- InquiresTotal
- OpenTotal
- ClosedTotalTermsNotPaid
- LatePaymentHistory001230
- LatePaymentHistory001260
- LatePaymentHistory001290Plus
- LatePaymentHistory132430
- LatePaymentHistory132460
- LatePaymentHistory132490Plus
- LatePaymentHistory25Plus30
- LatePaymentHistory25Plus60
- LatePaymentHistory25Plus90
